shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop_home, name='shop-home'),
    path('login-customer/', views.login_customer, name='login-customer'),
    path('check-product-quantity/', views.check_product_quantity, name='check-product-quantity'),
    path('create-order/', views.create_order, name='create-order'),
]

shopmanager/urls.py
from django.urls import path

from . import views


app_name = 'shopmanager'
urlpatterns = [
    path('', views.shopmanager_home, name='shopmanager-home'),
    path('shopmanager-view-orders/<int:pk>/', views.shopmanager_view_orders, name='shopmanager-view-orders'),
    path('export-orders-as-pdf/<int:pk>/', views.export_orders_as_pdf, name='export-orders-as-pdf'),
    path('register-applicant/', views.register_applicant, name='register-applicant'),
    path('dismiss-applicant/', views.dismiss_applicant, name='dismiss-applicant'),
]

svenska_svampar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(next_page='shop:shop-home'), name='logout'),
    path('', include('shop.urls')),
    path('shopmanager/', include('shopmanager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from django.contrib.contenttypes.models import ContentType
from datetime import timedelta
# Create your models here.





class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='Account', verbose_name='User')
    business_name = models.CharField(max_length=100, blank=True, unique=True, verbose_name='Business Name')
    organization_number = models.CharField(max_length=100, blank=True, unique=True, verbose_name='Organization Number', null=True)
    sweden_organization_number = models.CharField(max_length=100, blank=True, unique=True, verbose_name='Sweden Organization Number VAT NMMER', null=True)
    contact_person = models.CharField(max_length=100, blank=True, verbose_name='Contact Person')
    phone_number = models.CharField(max_length=100, blank=True, verbose_name='Phone Number')
    email = models.CharField(max_length=100, blank=True, verbose_name='Email')
    address = models.CharField(max_length=100, blank=True, verbose_name='Address')
    postal_code = models.CharField(max_length=100, blank=True, verbose_name='Postal Code')
    city = models.CharField(max_length=100, blank=True, verbose_name='City')
    user_class = models.ForeignKey('UserClass', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='User Class')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.business_name)
    
    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = 'Customers'
        verbose_name = 'Customer'



class Product(models.Model):
    name = models.CharField(max_length = 100, verbose_name='Name', db_index=True)
    stock = models.IntegerField(verbose_name='Stock')
    thumbnail = ProcessedImageField(upload_to='products/thumbnails/%Y/%m/%d/', processors=[ResizeToFill(550,550)], format='WEBP', options={'quality': 95}, verbose_name='Thumbnail', null=True)
    thumbnail_as_png = ImageSpecField(source='thumbnail',format='PNG')
    quantity_shipped = models.FloatField(default=1, verbose_name='1 box contains in kg')
    description = models.TextField(blank=True, verbose_name='Description', null=True)
    country_of_origin = models.CharField(max_length=100, blank=True, null=True, verbose_name='Country of Origin')
    temperature_storage = models.CharField(max_length=100, blank=True, null=True, verbose_name='Temperature Storage')
    storage_information = models.CharField(max_length=100, blank=True, null=True, verbose_name='Storage Information')

    energy_kj = models.CharField(max_length=10, blank=True, null=True, verbose_name='Energy (kJ)')
    energy_kcal = models.CharField(max_length=10,  blank=True, null=True, verbose_name='Energy (kcal)')
    fat = models.CharField(max_length=10, blank=True, null=True, verbose_name='Fat')
    saturated_fat = models.CharField(max_length=10, blank=True, null=True, verbose_name='Saturated Fat')
    monosaturated_fat = models.CharField(max_length=10,  blank=True, null=True, verbose_name='Monosaturated Fat')
    polyunsaturated_fat = models.CharField(max_length=10, blank=True, null=True, verbose_name='Polyunsaturated Fat')
    carbohydrates = models.CharField(max_length=10, blank=True, null=True, verbose_name='Carbohydrates')
    sugar = models.CharField(max_length=10, blank=True, null=True, verbose_name='Sugar')
    starch = models.CharField(max_length=10, blank=True, null=True, verbose_name='Starch')
    fiber = models.CharField(max_length=10, blank=True, null=True, verbose_name='Fiber')
    protein = models.CharField(max_length=10, blank=True, null=True, verbose_name='Protein')
    salt = models.CharField(max_length=10, blank=True, null=True, verbose_name='Salt')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    mail_status = models.BooleanField(default=True)
    sku = models.CharField(max_length=100, blank=True, null=True, verbose_name='Article Number')
    ean_code = models.CharField(max_length=100, blank=True, null=True, verbose_name='EAN Code')
    has_accordion = models.BooleanField(default=False, verbose_name='Has Accordion?')
    def __str__(self):
        return f'{self.name} - {self.stock} stock'
    
    class Meta:
        verbose_name_plural = 'Products'
        verbose_name = 'Product'

    
    @property
    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse(f'admin:{content_type.app_label}_{content_type.model}_change', args=(self.id,))


class UserClass(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    products = models.ManyToManyField(Product, through='ProductPrice', verbose_name='Products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse(f'admin:{content_type.app_label}_{content_type.model}_change', args=(self.id,))
    
    
    class Meta:
        verbose_name_plural = 'User Classes'
        verbose_name = 'User Class'


class ProductPrice(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Product')
    price = models.FloatField(verbose_name='Price')
    user_class = models.ForeignKey(UserClass, on_delete=models.CASCADE, verbose_name='User Class')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Price for {self.product.name} by class {self.user_class.name}'
    
    class Meta:
        verbose_name_plural = 'Product Prices'
        verbose_name = 'Product Price'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', null=True, blank=True)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name='User Profile')
    order_date = models.DateTimeField(auto_now_add=True, verbose_name='Order Date')
    subtotal_price = models.FloatField(null = True, verbose_name='Subtotal Price (excl. VAT)')
    total_price = models.FloatField(null = True, verbose_name='Total Price')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')
    is_mail_sent = models.BooleanField(default=False, verbose_name='Is Mail Sent?')
    invoice_number = models.CharField(max_length=100, blank=True, null=True, verbose_name='Invoice Number')
    invoice_ocr = models.CharField(max_length=100, blank=True, null=True, verbose_name='Invoice OCR')


    business_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Business Name')
    organization_number = models.CharField(max_length=100, blank=True, null=True, verbose_name='Organization Number')
    sweden_organization_number = models.CharField(max_length=100, blank=True, null=True, verbose_name='Sweden Organization Number')
    contact_person = models.CharField(max_length=100, blank=True, null=True, verbose_name='Contact Person')
    address = models.CharField(max_length=100, blank=True, null=True, verbose_name='Address')
    postal_code = models.CharField(max_length=100, blank=True, null=True, verbose_name='Postal Code')
    city = models.CharField(max_length=100, blank=True, null=True, verbose_name='City')


    @property
    def get_order_vat(self):
        return self.total_price - self.subtotal_price

    @property
    def get_10_days_ahead(self):
        return self.order_date + timedelta(days=10)

    def __str__(self):
        if self.user is None:
            return f'Order #{self.id} - {self.business_name}'
        else:
            return f'Order #{self.id} - {self.user_profile.business_name}'
        

    class Meta:
        verbose_name_plural = 'Orders'
        verbose_name = 'Order'
        ordering = ['-created_at']




    @property
    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse(f'admin:{content_type.app_label}_{content_type.model}_change', args=(self.id,))


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Order')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name='Product')
    quantity = models.IntegerField(verbose_name='Quantity')
    price_each = models.FloatField(verbose_name='Price Each')
    total_price = models.FloatField(verbose_name='Total Price')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_quantity_in_kg(self):
        return self.product.quantity_shipped * self.quantity

    def __str__(self):
        if self.product is not None:
            return f'Order #{self.order.id} - {self.product.name}'
        else:
            return f'Order #{self.order.id} - Deleted Product'

    class Meta:
        verbose_name_plural = 'Order Items'
        verbose_name = 'Order Item'

shopmanager/forms.py
from django import forms
from django.contrib.auth.models import User
from shop.models import UserProfile, UserClass


class Register_ApplicationForm(forms.Form):
    business_name = forms.CharField(max_length=100, required=True)
    city = forms.CharField(max_length=100, required=True)
    contact_person = forms.CharField(max_length=100, required=True)
    phone_number = forms.CharField(max_length=100, required=True)
    email = forms.CharField(max_length=100, required=True)
    address = forms.CharField(max_length=100, required=True)

shopmanager/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from wkhtmltopdf.views import PDFTemplateResponse
from shop.models import Order, OrderItem, UserProfile, Product, UserClass, ProductPrice
from .models import *
from .mail_api import send_mails
from .pdf_generation import generate_pdf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
# Create your views here.


def shopmanager_home(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            products = Product.objects.all().order_by('name')
            organizations = UserProfile.objects.all().values('id', 'business_name')
            register_applications = Register_Application.objects.filter(is_dismissed=False).order_by('-created_at')
            new_registrations_count = register_applications.count()
            user_classes = UserClass.objects.all().order_by('name').exclude(name='Admin')
            new_user_profile_url = reverse('admin:shop_userprofile_add')
            # for all user_classes get the product name and their prices
            
            context = {
                'organizations': organizations,
                'products': products,
                'new_registrations_count': new_registrations_count,
                'user_classes': user_classes,
                'register_applications': register_applications,
                'title': 'Shop Manager Home',
                'new_user_profile_url': new_user_profile_url,

            }
            return render(request, 'shopmanager/shopmanager_home.html', context)
        else:
            return HttpResponse('You are not authorized to view this page')
    else:
        return HttpResponse('You are not authorized to view this page')


def shopmanager_view_orders(request, pk):
    if request.user.is_authenticated and request.user.is_staff:
        if(pk == 0):
            orders = Order.objects.prefetch_related('orderitem_set').order_by('-created_at')
        else:
            orders = Order.objects.prefetch_related('orderitem_set').filter(user_profile__id=pk).order_by('-created_at')
        organizations = UserProfile.objects.all().values('id', 'business_name')
        register_applications = Register_Application.objects.filter(is_dismissed=False).order_by('-created_at')
        new_registrations_count = register_applications.count()
        current_user = UserProfile.objects.filter(id=pk).values('id', 'business_name').first()

        paginator = Paginator(orders, 20)  # Show 10 orders per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        

        context = {
            'orders': orders,
            'title': 'View Orders',
            'organizations': organizations,
            'new_registrations_count': new_registrations_count,
            'register_applications': register_applications,
            'title': 'Shopmanager Orders',
            'current_user': current_user,
            'page_obj': page_obj,
        }
        return render(request, 'shopmanager/view_orders.html', context)


def export_orders_as_pdf(request, pk):
    if request.user.is_authenticated and request.user.is_staff:
        order = Order.objects.prefetch_related('orderitem_set').filter(id=pk).first()
        if order.user is not None:
            organization = order.user_profile
            
            context = {
                'order': order,
                'organization': organization,
            }
            return PDFTemplateResponse(request, 'shopmanager/pdf_generation/delivery_note.html', context, cmd_options={'load-error-handling': 'ignore'})
        else:
            context = {
                'order': order,
            }
            return PDFTemplateResponse(request, 'shopmanager/pdf_generation/delivery_note_unregistered.html', context, cmd_options={'load-error-handling': 'ignore'})
    else:
        return HttpResponse('You are not authorized to view this page')



def register_applicant(request):
    if request.method == 'POST':
        business_name = request.POST.get('business_name')
        city = request.POST.get('city')
        contact_person = request.POST.get('contact_person')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        address = request.POST.get('address')
        business_type = request.POST.get('business_type')
        registration_note = request.POST.get('registration_note', None)
        print(business_name, city, contact_person, phone_number, email, address, business_type, registration_note)
        if business_name and city and contact_person and phone_number and email and address and business_type:
            register_application = Register_Application.objects.create(
                business_name=business_name,
                city=city,
                contact_person=contact_person,
                phone_number=phone_number,
                email=email,
                address=address,
                business_type=business_type,
                registration_note=registration_note,
            )
            register_application.save()
            return JsonResponse({'status': 'success', 'message': 'Application submitted successfully'}, status=200)
        else:
            return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)
        
    else:
        return HttpResponse('You are not authorized to view this page', status=401)
    

def dismiss_applicant(request):
    if request.method == 'POST':
        if request.user.is_authenticated and request.user.is_staff:
            try:
                applicant_id = request.POST.get('applicant_id')
                applicant = Register_Application.objects.get(id=applicant_id)
                applicant.is_dismissed = True
                applicant.save()
                return JsonResponse({'status': 'success', 'message': 'Applicant dismissed successfully'}, status=200)
            except:
                return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)
    else:
        return HttpResponse('You are not authorized to view this page', status=401)

shopmanager/templates/shopmanager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shopmanager/css/bootstrap_v1.css' %}">
    <link rel="stylesheet" href="{% static 'shopmanager/css/main.css' %}">
    
</head>
<body style="background-color:#f2f6fc!important">
    {% include 'shopmanager/includes/header.html' %}
    {% block content %}{% endblock content %}

    <script src="{% static 'shopmanager/js/jquery.js' %}"></script>
    <script src="{% static 'shopmanager/js/bootstrap.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

shopmanager/templates/shopmanager/shopmanager_home.html
{% extends 'shopmanager/base.html' %}
{% load static %}

{% block content %}
{% csrf_token %}
    <div class="container-xxl">
        <div class="row p-2 my-3 row-cols-lg-6 row-cols-md-4 row-cols-sm-2 g-4 text-center">
            <div class="col-12 w-100 text-primary">
                <h3>Stock Status</h3>
            </div>
            {% for product in products %}
                    <div class="col">
                        {% if product.stock > 50 %}
                        <div class="card bg-success text-white">
                        {% elif product.stock == 0 %}
                        <div class="card bg-danger text-white">
                        {% else %}
                        <div class="card bg-warning text-dark">
                        {% endif %}
                            <div class="card-body">
                                <p class="fw-bolder">{{ product.name }}</p>
                                <div>Stock: <span class="fw-bold">{{ product.stock }}</span></div>
                            </div>
                            <div class="card-footer">
                                <a href="{{ product.get_admin_url }}" target="_blank" class="btn btn-sm btn-dark">Update stock</a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <div class="row p-2 my-3 g-4 text-center">
            <div class="col-12 w-100 text-center text-primary">
                <h3>Prices per user class</h3>
            </div>
            {% for user_class in user_classes %}
            <div class="col col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card bg-dark text-white" >
                    <div class="card-header fw-bold d-flex justify-content-between align-items-center flex-wrap">
                        <div>
                            {{ user_class.name }}
                        </div>
                        <a href="{{ user_class.get_admin_url }}" class="btn btn-sm btn-primary" target="_blank">Edit</a>
                    </div>
                    <ul class="list-group list-group-flush bg-primary">
                    {% for product in user_class.productprice_set.all %}
                    <li class="list-group-item">{{ product.product.name }} - {{ product.price }} sek</li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}   
        </div>
        <div class="row p-2 my-3 g-4 text-left" id="new_registrations">
            <div class="col-12 w-100 text-center text-primary">
                <h3>New registrations</h3>
            </div>
            {% for applicant in register_applications %}
            <div class="col col-12 col-lg-6 col-xl-4 applicationHolder">
                <div class="card">
                    <div class="card-body">
                        <div class="text-bold text-primary pb-3 fs-5 fw-bold">{{ applicant.business_name }}<div class=" fw-normal fs-6 font-italic">{{ applicant.created_at }}</div></div>

                        <div><span class="fw-semibold">Contact:</span> {{ applicant.contact_person }}</div>
                        <div><span class="fw-semibold">Phone:</span> {{ applicant.phone_number }}</div>
                        <div><span class="fw-semibold">Email:</span> {{ applicant.email }}</div>
                        <div><span class="fw-semibold">City:</span> {{ applicant.city }}</div>
                        <div><span class="fw-semibold">Address:</span> {{ applicant.address }}</div>
                        <div><span class="fw-semibold">Business type:</span> {{ applicant.business_type }}</div>
                        {% if applicant.registration_note %}
                        <div><span class="fw-semibold">Registration note:</span> {{ applicant.registration_note }}</div>
                        {% endif %}
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <button class="btn btn-sm btn-secondary dismiss-userBtn" data-registrant-id="{{ applicant.id }}">Dismiss</button>
                        <a href="{{new_user_profile_url}}"class="btn btn-sm btn-success" target="_blank">Approve</a>
                    </div>
                    

                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12">
            
        </div>

        
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'shopmanager/js/main.js' %}"></script>
{% endblock scripts %}

shopmanager/templates/shopmanager/view_orders.html
{% extends 'shopmanager/base.html' %}
{% load static %}

{% block content %}
<div class="container-xxl">
    <div class="row p-2 my-3 g-4">
        <div class="col-12 text-primary">
            {% if current_user.business_name %}
                <h3>Orders for {{ current_user.business_name }}</h3>
            {% else %}
                <h3>All orders</h3>
            {% endif %}
        </div>
        {% for order in page_obj %}
        <div class="col col-12 col-lg-6 col-xl-4">
            <div class="card border border-success">
                {% if order.user %}
                  <div class="card-header fw-semibold bg-success text-white">{{ order.user_profile.business_name }}</div>
                {% else %}
                <div class="card-header fw-semibold bg-success text-white">{{ order.business_name }} (Unregistered user)</div>
                {% endif %}
                <div class="card-body">
                  <div class="d-flex flex-wrap justify-content-between align-items-center">
                    <div class="card-text fw-semibold fs-5">Order #{{ order.id }}</div>
                    <div class="card-text fw-semibold">{{ order.total_price }} sek</div>
                  </div>
                  <div class="pb-3">{{ order.created_at|date:"y/m/d H:i:s" }}</div>
                  {% for item in order.orderitem_set.all %}
                        <div class="card-text">{{ item.product.name }} x {{ item.quantity }} - {{ item.total_price }} sek</div>
                  {% endfor %}
                  <div class="d-flex flex-wrap justify-content-between align-items-center">
                    <a href="{{ order.get_admin_url }}" class="btn btn-sm btn-dark mt-3" target="_blank">Edit</a>
                    <a href="{% url 'shopmanager:export-orders-as-pdf' order.id %}" class="btn btn-sm btn-primary mt-3" target="_blank">Generate PDF</a>
                </div>
                </div>
              </div>
        </div>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
            {% endif %}
              <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
              </li>
              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
                {% endif %}
            </ul>
          </nav>
    </div>


</div>

{% endblock content %}

{% block scripts %}
    <script src="{% static 'shopmanager/js/main.js' %}"></script>
{% endblock scripts %}