shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop_home, name='shop-home'),
    path('login-customer/', views.login_customer, name='login-customer'),
    path('check-product-quantity/', views.check_product_quantity, name='check-product-quantity'),
    path('create-order/', views.create_order, name='create-order'),
]

shopmanager/urls.py
from django.urls import path

from . import views


app_name = 'shopmanager'
urlpatterns = [
    path('', views.shopmanager_home, name='shopmanager-home'),
    path('shopmanager-view-orders/<int:pk>/', views.shopmanager_view_orders, name='shopmanager-view-orders'),
    path('export-orders-as-pdf/<int:pk>/', views.export_orders_as_pdf, name='export-orders-as-pdf'),
    path('register-applicant/', views.register_applicant, name='register-applicant'),
    path('dismiss-applicant/', views.dismiss_applicant, name='dismiss-applicant'),
]

svenska_svampar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(next_page='shop:shop-home'), name='logout'),
    path('', include('shop.urls')),
    path('shopmanager/', include('shopmanager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/views.py
import logging
from django.shortcuts import render
from django.http import JsonResponse
import json
from shop.models import *
from shopmanager.models import Register_Application
from django.contrib.auth import authenticate, login
from shopmanager.mail_api import send_mails
from random import randint
from shopmanager.mail_api import send_mails
from shopmanager.pdf_generation import generate_pdf


logger = logging.getLogger('shop')

def shop_home(request):
    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)
        user_class = user_profile.user_class
        products = Product.objects.all().order_by('name')
        product_prices = {}
        for product in products:
            try:
                price = ProductPrice.objects.get(product=product, user_class=user_class)
                product_prices[product] = price
            except ProductPrice.DoesNotExist:
                product_prices[product] = None


        context = {
            'user_profile': user_profile,
            'product_prices': product_prices,
        }
        if request.user.is_staff:
            context['is_admin'] = True
            context['new_registrations_count'] = Register_Application.objects.filter(is_dismissed=False).count()
    else:
        user_profile = None
        products = Product.objects.all()
        product_prices = {}
        for product in products:
            product_prices[product] = None
        context = {
            'user_profile': user_profile,
            'product_prices': product_prices,
        }

    return render(request, 'shop/shop_home.html', context=context)


def check_product_quantity(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            product_id = int(request.GET.get('product_id'))
            quantity = int(request.GET.get('quantity'))

            try:
                product = Product.objects.get(id=product_id)
            except Product.DoesNotExist:
                return JsonResponse({'error': 'Product does not exist.'}, status=400)
            
            if (quantity > product.stock):
                user_profile = UserProfile.objects.get(user=request.user)
                send_mails.failed_add_to_cart_mail(product, quantity, user_profile)
                return JsonResponse({'error': 'Not enough stock.'}, status=400)
            else:
                return JsonResponse({'message': 'Enough stock.'}, status=200)
            
        else:
            return JsonResponse({'error': 'Not authenticated.'}, status=400)
        
    else:
        return JsonResponse({'error': 'Wrong request method.'}, status=400)
    

def create_order(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user
            user_profile = UserProfile.objects.get(user=user)
            user_class = user_profile.user_class
            cart_items = json.loads(request.POST.get('cartItems'))
            if not cart_items:
                return JsonResponse({'error': 'Cart is empty.'}, status=400)
           # print(cart_items)
            insufficient_stock_items = []
            email_insufficient_stock_items = []
            for prod_id, quantity in cart_items.items():
                product_id = int(prod_id)
                quantity = int(quantity)
                try:
                    product = Product.objects.get(id=product_id)
                except Product.DoesNotExist:
                    return JsonResponse({'error': 'Product does not exist.'}, status=400)
                
                if quantity > product.stock and product.stock > 0:
                    insufficient_stock_items.append(product_id)
                    invalid_product_dict = {
                        'name': product.name,
                        'quantity': quantity,
                        'stock_left': product.stock,
                    }
                    email_insufficient_stock_items.append(invalid_product_dict)
                    
            
            if insufficient_stock_items:
                send_mails.insufficient_stock_mail(user_profile, email_insufficient_stock_items)
                return JsonResponse({
                    'error': 'Not enough stock for some items',
                    'insufficient_stock_items': insufficient_stock_items
                    }, status=400)
            else:
                order = Order.objects.create(user=user, user_profile = user_profile)
                order_subtotal = 0
                order_total = 0
                created_products = []
                for prod_id, quantity in cart_items.items():
                    product = Product.objects.get(id=int(prod_id))
                    product_price = ProductPrice.objects.filter(product=product, user_class=user_class).values_list('price', flat=True).get()
                    order_subtotal += product_price * quantity
                    OrderItem.objects.create(order=order, product=product, quantity=quantity,
                                              price_each = product_price, total_price = product_price * quantity)
                    product.stock -= quantity
                    product.save()
                    product_dict = {
                        'id': product.id,
                        'name': product.name,
                        'quantity': quantity,
                        'price': product_price,
                        'total_price': product_price * quantity,
                    }
                    created_products.append(product_dict)

                order_total = order_subtotal + (order_subtotal * 0.12)
                order.subtotal_price = order_subtotal
                order.total_price = order_total
                order.save()
                send_mails.new_order_mail(order, generate_pdf.export_orders_as_pdf(user_profile  ,order))
                return JsonResponse(
                    {
                    'message': 'Order created.',
                    'products': created_products,
                    'order_total': order_total,
                    }, status=200)
                
        else:
            return JsonResponse({'error': 'Not authenticated.'}, status=400)
        

def shop_login(request):
    if request.user.is_authenticated:
        return render(request, 'shop/shop_home.html')
    else:
        return render(request, 'shop/login.html')
    

def login_customer(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)

        if username and password:
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return JsonResponse({'message': 'Login successful.'}, status=200)
            else:
                return JsonResponse({'error': 'Invalid credentials.'}, status=400)
        else:
            return JsonResponse({'error': 'Invalid credentials.'}, status=400)
    else:
        return JsonResponse({'error': 'Wrong request method.'}, status=400)
    

shop/templates/shop/includes/footer.html
{% load static %}
<div style="background-image:url('{% static 'shop/assets/mushrooms_divider.png' %}'); height:80px; background-size:contain; opacity:0.8; z-index:1000000" class="mt-4"></div>
<footer class="shadow-lg">
    <div class=" bg-dark text-light pt-4 px-4 pb-1">
        <div class="container-xxl p-4">
            <div class="row g-4">
                <div class="col-12 col-md-4 d-flex justify-content-md-start flex-column align-items-md-start align-items-center">
                    <h4 class="text-center text-md-start">Svenska Svampar</h4>
                    <a href="https://www.instagram.com/svenska_svampar/?igshid=OGQ5ZDc2ODk2ZA%3D%3D" target="_blank" class="ps-2 text-light text-center text-md-start"><img src="{% static 'shop/assets/icons/instagram.svg' %}" alt="" width="24" height="24" style="filter:invert()" class="me-2">Add us on instagram</a>
                </div>
                <div class="col-12 col-md-4 d-flex justify-content-md-start flex-column align-items-center">
                    <h4>Contact</h4>
                    <div class="d-flex-align-items-start justify-content-start flex-column">
                        <div class="ps-2 text-center text-md-start">
                            <a href="tel:+46736667167" class="text-reset  text-light ">
                                <img src="{% static 'shop/assets/icons/phone.svg' %}" alt="" width="24" height="24" style="filter:invert()" class="me-2">+46 73 666 71 67</a>
                        </div>
                        <div class="ps-2 pt-2 text-center text-md-start">
                            <a href="mailto:info@svenskasvampar.se" class="text-reset  text-light "><img src="{% static 'shop/assets/icons/mail.svg' %}" alt="" width="24" height="24" style="filter:invert()" class="me-2">
                            info@svenskasvampar.se</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4 d-flex justify-content-md-start flex-column align-items-center">
                    <h4>Address</h4>
                    <p class="ps-2 text-light text-center text-md-start">Mitson Bär & Svamp AB<br>
                    Stinavägen 3<br>
                    691 54 KARLSKOGA
                    </p>
                </div>
                <div class="col-12 d-flex justify-content-center">
                    <h1>Sverige</h1>
                </div>
            </div>

        </div>
        <div class="w-100 text-center">
            <hr class="bg-light">
            <p class="text-light">© 2023 Mitson Bär & Svamp AB</p>
        </div>
    </div>
</footer>
<!-- Footer -->
<!-- Footer -->

  <!-- Footer -->

shop/templates/shop/includes/header.html
{% load static %}


<nav class="navbar navbar-expand-lg bg-dark sticky-top" data-bs-theme="dark" co>
    <div class="container-xxl ">
        <a class="navbar-brand fst-italic" href="#">
            <img src="{% static 'shop/assets/logo_header.png' %}" alt="Logo" width="81" height="57" class="d-inline-block align-text-middle">
            Svenska Svampar
          </a>
    
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#shopmanager-navbarNav" aria-controls="shopmanager-navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="shopmanager-navbarNav">
            <div class="navbar-nav">
                {% if request.user.is_staff %}
                    <a href="{% url 'shopmanager:shopmanager-home' %}" class="nav-link">Shopmanager</a>
                    <a href="{% url 'shopmanager:shopmanager-home' %}#new_registrations" class="nav-link" style="position:relative">New Registrations<span style="position:relative;bottom:5px;left:2px;font-weight:600;" class="text-warning">{{ new_registrations_count }}</span></a>
                    <a href="{% url 'shopmanager:shopmanager-view-orders' pk=0 %}" class="nav-link">View Orders</a>
                {% endif %}
                <!-- <a href="#" class="nav-link">About us</a> !-->
            </div>
            <div class="navbar-nav">
                {% if not user_profile %}    
                    <p class="nav-link m-0 cursor-pointer">Ask to register</p>
                    <p class="nav-link m-0 cursor-pointer" id="navLogin">Login</p>
                {% else %}
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                {% endif %} 
            </div>
        </div> 
        
    </div>
</nav>